# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimr" do
  name "aimr"
  desc "AI-assisted Git MR/PR analysis and commit generator"
  homepage "https://github.com/centrium/aimr"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimr"

  on_macos do
    on_intel do
      url "https://github.com/centrium/aimr/releases/download/v#{version}/aimr_#{version}_macOS_amd64.tar.gz"
      sha256 "3fc7a09f21d39e413232ae1cf368601536da9192f2fd917007a9f78d2f44cbd0"
    end
    on_arm do
      url "https://github.com/centrium/aimr/releases/download/v#{version}/aimr_#{version}_macOS_arm64.tar.gz"
      sha256 "b51042604303fddb28f578a805acc1fa55a495b35cea3772d6a2200bb80ad4fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/centrium/aimr/releases/download/v#{version}/aimr_#{version}_linux_amd64.tar.gz"
      sha256 "2434f3eb2819a395b3a87ac1985c1818376bd70661151df7daf9ff793d2a47dc"
    end
    on_arm do
      url "https://github.com/centrium/aimr/releases/download/v#{version}/aimr_#{version}_linux_arm64.tar.gz"
      sha256 "107fe12caa36d406699e15e18ae3723d1f4701c365020774e8ddbca4d93b5b58"
    end
  end

  # No zap stanza required
end
