# This file was generated by GoReleaser. DO NOT EDIT.
cask "aimr" do
  name "aimr"
  desc "AI-assisted Git MR/PR analysis and commit generator"
  homepage "https://github.com/centrium/aimr-releases"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aimr"

  on_macos do
    on_intel do
      url "https://github.com/centrium/aimr-releases/releases/download/v#{version}/aimr_#{version}_macOS_amd64.tar.gz"
      sha256 "9a4548148f04ac61ae9be48854f687f4248397aee315ff973374e07443cfc97a"
    end
    on_arm do
      url "https://github.com/centrium/aimr-releases/releases/download/v#{version}/aimr_#{version}_macOS_arm64.tar.gz"
      sha256 "4e93ba087316a18f50fc022a1af4a31861270f89aad9e988e4f414738290a940"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/centrium/aimr-releases/releases/download/v#{version}/aimr_#{version}_linux_amd64.tar.gz"
      sha256 "cf472b2782ccfb61cbd31f5eb33514178bdaf5b1827877c86dea570074d7b21c"
    end
    on_arm do
      url "https://github.com/centrium/aimr-releases/releases/download/v#{version}/aimr_#{version}_linux_arm64.tar.gz"
      sha256 "964c3dd369869a05e55e2a7eff4aa3f9c4cdb3a757e318e4dd8c70935bbcea76"
    end
  end

  # No zap stanza required
end
