# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimr < Formula
  desc "AI-assisted Git MR/PR analysis and commit generator"
  homepage "https://github.com/centrium/aimr-releases"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.3/aimr_0.1.3_macOS_amd64.tar.gz"
      sha256 "7629d922bfb7c271ff33627d30b67d9f2b3ee16da3f2b413b7538575da6d2583"

      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.3/aimr_0.1.3_macOS_arm64.tar.gz"
      sha256 "3651c2e58cf53b9b58a1647139eb760bfb470018f1cf03ccba413d211367cd97"

      def install
        bin.install "aimr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.3/aimr_0.1.3_linux_amd64.tar.gz"
      sha256 "42174b8e2e08dff3564fbc2d0a6f36641e4730f1c768a672b694ccbc716bb439"
      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.3/aimr_0.1.3_linux_arm64.tar.gz"
      sha256 "2ac0a2a72c42df62b04908ffa1ca578f6c78b0c746e4e1e73cd54deb88b2e17a"
      def install
        bin.install "aimr"
      end
    end
  end
end
