# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimr < Formula
  desc "AI-assisted Git MR/PR analysis and commit generator"
  homepage "https://github.com/centrium/aimr-releases"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.2/aimr_0.1.2_macOS_amd64.tar.gz"
      sha256 "0f1036d6f15725ecbf6081875076902a5e92c484b5dbace97d0c8c20bfc8808f"

      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.2/aimr_0.1.2_macOS_arm64.tar.gz"
      sha256 "d418b0abb747028d1f5eb70bcb39e459a7a7fb7e0be3ea30c33b9e7ef0abd5d9"

      def install
        bin.install "aimr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.2/aimr_0.1.2_linux_amd64.tar.gz"
      sha256 "9b370414b2209945cb2ac6252ecc067aace61e686cd8fba452cd08fa53a06197"
      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.1.2/aimr_0.1.2_linux_arm64.tar.gz"
      sha256 "cf2b509b3b781c3a43e2286f9dda7dec31910c3319a629c8bdbb2357c44e0390"
      def install
        bin.install "aimr"
      end
    end
  end
end
