# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aimr < Formula
  desc "AI-assisted Git MR/PR analysis and commit generator"
  homepage "https://github.com/centrium/aimr-releases"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.2.0/aimr_0.2.0_macOS_amd64.tar.gz"
      sha256 "7b17ab6e5bbdcdd0b171b67d34d73668b8aa854b2f60ea79550a1d1f2df500b9"

      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.2.0/aimr_0.2.0_macOS_arm64.tar.gz"
      sha256 "554ac0525d6cba4e2aa07e87000c31cf91aa02560bdc71c3dc654970e4382d6f"

      def install
        bin.install "aimr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.2.0/aimr_0.2.0_linux_amd64.tar.gz"
      sha256 "a0753fb808b9689f6f677bfba75b4c636758c6c6d03d41d3b4543b6ec5d406bb"
      def install
        bin.install "aimr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/centrium/aimr-releases/releases/download/v0.2.0/aimr_0.2.0_linux_arm64.tar.gz"
      sha256 "7a8bd334190f2eafed2bd6a7b333be42827956b3e08e4c77255c64c3b5b3980c"
      def install
        bin.install "aimr"
      end
    end
  end
end
